<a href="https://colab.research.google.com/github/raizexo/black-friday-analysis/blob/master/Black_Friday_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Black Friday Sales Dataset Analysis

In [0]:
#Importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [2]:
#Fetching the dataset from GitHub
!git clone https://github.com/raizexo/black-friday-analysis.git
%cd black-friday-analysis

Cloning into 'black-friday-analysis'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.
/content/black-friday-analysis


In [3]:
#Importing the Training and Testing Datasets
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head(5)

User_ID Product_ID Gender  ... Product_Category_2  Product_Category_3 Purchase
0  1000001  P00069042      F  ...                NaN                 NaN     8370
1  1000001  P00248942      F  ...                6.0                14.0    15200
2  1000001  P00087842      F  ...                NaN                 NaN     1422
3  1000001  P00085442      F  ...               14.0                 NaN     1057
4  1000002  P00285442      M  ...                NaN                 NaN     7969

[5 rows x 12 columns]

In [4]:
train.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [0]:
#Filling the NAN values in the training set with zeros
train = train.fillna(0)
from sklearn.preprocessing import LabelEncoder
train = np.array(train)

for i in range(train.shape[1]-1):
    lbl = LabelEncoder()
    lbl.fit(list(train[:,i]))
    train[:, i] = lbl.transform(train[:, i])

In [6]:
print(train)

[[0 672 0 ... 0 0 8370]
 [0 2376 0 ... 5 11 15200]
 [0 852 0 ... 0 0 1422]
 ...
 [5886 3568 0 ... 0 0 137]
 [5888 3568 0 ... 0 0 365]
 [5889 3566 0 ... 0 0 490]]


In [0]:
#Dividing the training set into X and y for learning
X = train[:,:11]
y = train[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)

#Model 1 
A simple Random Forest Regressor with no changes in the parameters.


In [8]:
rfc = RandomForestRegressor()
rfc.fit(X_train,y_train)
prediction = rfc.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [9]:
score = mean_squared_error(y_test,prediction)
print(score)

8083354.1505835615
